/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrOctetString;

public class CosemDateTime extends AxdrOctetString {

    public static final int length = 12;

    public CosemDateTime() {
        super(length);
    }

    public CosemDateTime(byte[] octetString) {
        super(length, octetString);
    }

}
